version: '3'
services:
  #Neo4j Service
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: unless-stopped
    tty: true
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,algo.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,algo.*"
    networks:
      - neo4j
    volumes:
    - neo4j-data:/data
    - neo4j-logs:/logs
    - neo4j-plugins:/plugins

#Neo4j network
networks:
  neo4j:
    driver: bridge

#Neo4j volume
volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-plugins:
    driver: local
    