version: '3'
services:
  #Neo4j Service
  neo4j:
    image: neo4j:enterprise
    container_name: neo4j
    restart: unless-stopped
    tty: true
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      #NEO4JLABS_PLUGINS: "[\"apoc\"]"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,algo.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,algo.*"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    networks:
      - neo4j
    volumes:
    - neo4j-data:/data
    - neo4j-logs:/logs
    - neo4j-plugins:/plugins
  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    restart: unless-stopped
    tty: true
    ports:
      - "389:389"
    environment:
      LDAP_ORGANISATION: "LearningNeo4jWithJerome"
      LDAP_DOMAIN: "learningneo4j.com"
      LDAP_BIND_DN: "cn=admin,dc=learningneo4j, dc=com"
      LDAP_BASE: "dc=learningneo4j, dc=com"
      LDAP_ADMIN_PASSWORD: "agentSmith"
    volumes:
      - ./data/ldap/environment/:/container/environment/01-custom/
    networks:
      - neo4j

#Neo4j network
networks:
  neo4j:
    driver: bridge

#Neo4j volume
volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-plugins:
    driver: local
    